### ISSUE TITLE
yaml parse fails if envOr is used in url property in database.yml

### ISSUE THREAD

**Issue by mkozjak** [markbates/pop#100]
In example, you can't use
`test:
  url: {{ envOr "TEST_DB_URL" "postgres://user:password@127.0.0.1:5432/db_test?sslmode=disable" }}`

It will fail with `couldn't unmarshal config to yaml: yaml: line 1: did not find expected alphabetic or numeric character`

Should we edit the README portion of envOr?

**Comment by markbates** [comment]
Where do you see that? I can't seem to find it anywhere.

**Comment by mkozjak** [comment]
```sh
fgrep -r 'did not find expected alphabetic or numeric character' vendor/*
vendor/gopkg.in/yaml.v2/scannerc.go: "did not find expected alphabetic or numeric character")
```

```sh
fgrep -r 'yaml.v2' vendor/github.com/markbates/*  
vendor/github.com/markbates/pop/config.go:	"gopkg.in/yaml.v2"
```

**Comment by markbates** [comment]
I meant where are you seeing that example?

**Comment by markbates** [comment]
It should be defined like this:

```yaml
test: 
  url: {{ envOr "TEST_DB_URL" "postgres://user:password@127.0.0.1:5432/db_test?sslmode=disable" }}
```

YAML is strict on formatting

**Comment by mkozjak** [comment]
Yup, that's exactly how I use it. Formatting crashed here and took out the NFCR character, I guess.
If I use `url: "postgres://user:password@127.0.0.1:5432/db_test?sslmode=disable"` it works.

**Comment by markbates** [comment]
I use it all the time, but I put `"` around it all:

```yaml
test: 
  url: "{{ envOr "TEST_DB_URL" "postgres://user:password@127.0.0.1:5432/db_test?sslmode=disable" }}"
```

**Comment by mkozjak** [comment]
@markbates That one breaks pretty bad and also messes up vim highlighting. Maybe you meant single ticks. Doesn't work either. All I get is `Could not find connection named test!`.

```
development:
  dialect: postgres
  database: db_dev
  user: usere
  password: passw
  host: {{ envOr "DB_HOSTNAME" "127.0.0.1" }}
  pool: 5

test:
  url: "{{ envOr "TEST_DB_URL" "postgres://ut:pt@127.0.0.1:5432/db_test?sslmode=disable" }}"

production:
  url: "{{ envOr "DB_URL" "postgres://up:pp@127.0.0.1:5432/db_production?sslmode=disable" }}"
```
