### ISSUE TITLE
mysql dialect doesn't respect port and host parameters

### ISSUE THREAD

**Issue by slashk** [markbates/pop#15]
The MySQL `createDB` and `DropDB` ignore the `database.yml` host and port parameters.

database.yml
```yaml
development:
  dialect: "mysql"
  database: "mtbcal_development"
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "root"

test:
  dialect: "mysql"
  database: "mtbcal_test"
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "root"

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@(127.0.0.1:3306)/mtbcal_production"}}
```

running soda (using pop)
```
$ soda  create -a -d
Soda v3.10.0

[POP]: Loading config file from /Users/kpepple/go/src/github.com/slashk/mtbcal/database.yml
[POP] 2017/01/07 16:51:34 Create mtbcal_development (root:root@(127.0.0.1:3306)/mtbcal_development?parseTime=true&multiStatements=true&readTimeout=1s)
[POP] 2017/01/07 16:51:34 Create mtbcal_test (root:root@(127.0.0.1:3306)/mtbcal_test?parseTime=true&multiStatements=true&readTimeout=1s)
[POP] 2017/01/07 16:51:34 Create mtbcal_production (mysql://root:root@(127.0.0.1:3306)/mtbcal_production)
$ mysqlshow -u root -h 127.0.0.1 -proot
mysqlshow: [Warning] Using a password on the command line interface can be insecure.
+--------------------+
|     Databases      |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
```
