### ISSUE TITLE
CreateDB on PostgreSQL fails

### ISSUE THREAD

**Issue by misham** [markbates/pop#175]
The problem is when creating the database for a user that doesn't have any other privileges.  To replicate:

Create a new user:

```
#>psql template1
create role test_user with createdb login password 'test123';
\q
```

Setup config file as follows:

```yaml
default: &default
  dialect: postgres
  host: 127.0.0.1
  pool: 5
  user: test_user
  password: test123

development:
  <<: *default
  database: my_testing_db
```

Then try to create a DB:

```
#> soda create -a
```

You'll get an error to the effect of:

```
Error: couldn't create database my_testing_db: error creating PostgreSQL database my_testing_db: pq: database "test_user" does not exist
```

The solution is for the client to connect to `template1` database before running the create SQL.  This should, also, be the case for dropping a database as well.
